version: '3.8'

services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra-trabajo
    environment:
      - CASSANDRA_CLUSTER_NAME=my_cassandra_cluster
      - CASSANDRA_NUM_TOKENS=256
      - CASSANDRA_START_RPC=true
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
    ports:
      - "9042:9042"  # Puerto para CQL (Cassandra Query Language)
    volumes:
      - cassandra_data:/var/lib/cassandra  # Volumen para persistir datos

volumes:
  cassandra_data:
    driver: local