version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: MYSQL_trabajo
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes  # Permite iniciar sin contraseña
    ports:
      - "3306:3306"  # Puerto de MySQL
    volumes:
      - mysql_data:/var/lib/mysql       # Volumen para persistir datos

volumes:
  mysql_data:
    driver: local